config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  get    'account_activation',  to: 'users#account_activation'
  get    'password_reset',      to: 'users#password_reset'
  post   'edit_pass',           to: 'users#edit_pass'
  post   'search',              to: 'users#search'
  post   'set',                 to: 'posts#add_next'
  get    'search',              to: 'users#index'
  post   'add_friend',          to: 'users#create_friend'
  delete 'delete_friend',       to: 'users#destroy_friend'
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'
  resources :users do
    resources :posts do
      post "like", on: :member
      post "dislike", on: :member
    end
    resources :images
    resources :comments
    resources :messages
    patch :friends, on: :member
    get :friends, on: :member
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :images, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friend_relations, dependent: :destroy
  has_many :friends, :through => :friend_relations
  has_many :inverse_friend_relations, :class_name => "FriendRelation",
           :foreign_key => "friend_id", dependent: :destroy
  has_many :inverse_friends, :through => :inverse_friend_relations, :source => :user
  has_many :messages
  has_many :inverse_messages, :class_name => "Message",
           :foreign_key => "receiver_id"
  has_many :ratings, dependent: :destroy
  has_many :estimator, :through => :ratings
  has_many :inverse_ratings, :class_name => "Rating",
           :foreign_key => "estimator_id", dependent: :destroy

  before_save { self.email = email.downcase }
  before_create :create_activation_digest
  attr_accessor :activation_token, :remember_token
  validates :name, presence: true,
                   length: { in: 3..15 },
                   format: { with: /\A[a-zA-Z]+-{0,1}[a-zA-Z]+\z/ }
  validates :surname, presence: true,
                      length: { in: 3..15 },
                      format: { with: /\A[a-zA-Z]+-{0,1}[a-zA-Z]+\z/ }
  validates :gender, presence: true,
                     acceptance: { accept: ['male', 'female'], message: "Specify your gender" }
  validates :email, presence: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true,
                       length: { minimum: 5 },
                       format: { with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9]*\z/,
                                 message: "must include lower, upper letter and num"}
  has_secure_password

  def all_relations
    FriendRelation.where('CAST(user_id AS text) LIKE ? OR CAST(friend_id AS text) LIKE ?', self.id.to_s, self.id.to_s)
  end

  def all_friends
    ids = self.friends.map {|men| men.id} + self.inverse_friends.map {|men| men.id}
    User.where('CAST(id AS INT) IN (?)', ids)
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user,   only: [:edit, :update, :edit_pass]
  before_action :logged_for_action, only: [:show, :search, :index, :friends,
                                           :create_friend, :destroy_friend]

  def new
    if logged?
      @user = current_user
      @friends = get_nine_friends @user
      @post = Post.new
      @comment = Comment.new
      @posts = @user.posts.last(10).reverse
    else
      @user = User.new()
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      UserMailer.account_activation(@user).deliver_now
      @friends = get_nine_friends @user
      @post = Post.new
      @comment = Comment.new
      @posts = @user.posts.last(10).reverse
      @page = "profile"
    else
      @page = "back"
    end

    respond_to do |format|
      format.js
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @friends = get_nine_friends @user
    @post = Post.new
    @comment = Comment.new
    @posts = @user.posts.last(10).reverse
    respond_to do |format|
      format.js
    end
  end

  def edit
    @user = current_user
    respond_to do |format|
      format.js
    end
  end

  def update
    @user = current_user
    if User.new(validation_hash).valid?
      @user.update_attribute(:name, params[:user][:name])
      @user.update_attribute(:surname, params[:user][:surname])
    end
    @friends = get_nine_friends @user
    @post = Post.new
    @comment = Comment.new
    @posts = @user.posts.last(10).reverse
    respond_to do |format|
      format.js
    end
  end

  def edit_pass
    @user = current_user
    @user.authenticated?(:password, params[:user][:last_password])
    @user.update_attributes(:password => params[:user][:password],
                              :password_confirmation => params[:user][:password_confirmation])
    @friends = get_nine_friends @user
    @post = Post.new
    @comment = Comment.new
    @posts = @user.posts.last(10).reverse
    respond_to do |format|
      format.js
    end
  end

  def account_activation
  end

  def password_reset
  end

  def search
    line = params[:user][:name]
    @search = []
    User.all.each do |user|
      @search<<user if (line.include?user.name)||
                      (line.include?user.surname)||
                      (user.name.include?line)||
                      (user.name.include?line)
    end
    respond_to do |format|
      format.js
    end
  end

  def friends
    @user = User.find_by(id: (params[:id]||current_user.id))
    @friends = @user.all_friends
    respond_to do |format|
      format.js
    end
  end

  def create_friend
    relation = FriendRelation.new(friend_relation_params)
    relation.friend_id = current_user.id
    relation.save
    @user = User.find_by(id: params[:friend_relation][:user_id])
    @friends = get_nine_friends @user
    @posts = @user.posts.paginate(page: params[:page], per_page: 10).order('id DESC')
    @post = Post.new
    @comment = Comment.new
    respond_to do |format|
      format.js
    end
  end

  def destroy_friend
    @user = User.find_by(id: params[:user][:user_id])
    relation = (current_user.all_relations.find_by(friend_id: @user.id)||current_user.all_relations.find_by(user_id: @user.id))
    relation.destroy
    @posts = @user.posts.paginate(page: params[:page], per_page: 10).order('id DESC')
    @post = Post.new
    @comment = Comment.new
    @profile = params[:user][:profile]
    if @profile == 'false'
      @friends = get_nine_friends current_user
      @user = current_user
    else
      @friends = get_nine_friends @user
    end
    respond_to do |format|
      format.js
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :surname, :gender, :email, :password, :password_confirmation)
    end

    def friend_relation_params
      params.require(:friend_relation).permit(:user_id)
    end

    def validation_hash
      { :name => params[:user][:name],
        :surname => params[:user][:surname],
        :gender => 'male',
        :email => 'true_email@exemple.com',
        :password => 'Validpass1',
        :password_confirmation => 'Validpass1' }
    end

    def correct_user
      redirect_to root_path unless (current_user == User.find_by(id: params[:id]))
    end
end

app/helpers/users_helper.rb
require 'uri'

module UsersHelper
  def get_avatar user
    user.images.order('id DESC').all.each {|img| return img.image.avatar.url if img.avatar}
    nil
  end

  def get_ico user
    user.images.order('id DESC').all.each {|img| return img.image.thumb.url if img.avatar}
  end

  def get_nine_friends user
    user.all_friends.count < 10 ? user.all_friends : user.all_friends.limit(9)
  end

  def is_friend? user
    current_user.all_friends.include?(user)
  end

  def date_format strtime
    strtime.strftime('%B %d, %H:%M:%S')
  end

  def post_comments post
    Comment.where('CAST(post_id AS text) LIKE ?', post.id.to_s)
  end

  def author comment
    User.find_by(id: comment.user_id)
  end

  def creator post
    User.find_by(id: post.user_id)
  end

  def news
    friend_ids = current_user.friends.map {|men| men.id} + current_user.inverse_friends.map {|men| men.id}
    Post.where('CAST(user_id AS INT) IN (?)', friend_ids)
  end

  def new_images
    friend_ids = current_user.friends.map {|men| men.id} + current_user.inverse_friends.map {|men| men.id}
    Image.where('CAST(user_id AS INT) IN (?)', friend_ids)
  end

  def get_utube text
    url = URI.extract(text)
    url[0] if !(url.count==0)
  end

  def get_user msg
    user = User.find_by(id: msg.user_id)
  end
end

app/views/users/_create_form.html.erb
<div class="registration">
  <%= form_for @user, remote: true do |form| %>
    <%= form.label :name, class: "move-down" %>
    <%= form.text_field :name, placeholder: "Your name" %><br>
    <%= form.label :surname %>
    <%= form.text_field :surname, placeholder: "Your surname" %><br>
    <%= form.radio_button :gender, 'male' %>
    <%= label :gender_male, 'Male' %>
    <%= form.radio_button :gender, 'female' %>
    <%= label :gender_female, 'Female' %><br>
    <%= form.label :email %>
    <%= form.text_field :email, placeholder: "Your emale" %><br>
    <%= form.label :password %>
    <%= form.password_field :password, placeholder: "Your password" %><br>
    <%= form.label :password_confirmation, hidden: :true %>
    <%= form.label :confirm %>
    <%= form.password_field :password_confirmation, placeholder: "Confirm password" %><br>

    <% if @user.errors.any? %>
      <ul class="error-msg">
        <% @user.errors.full_messages.each do |error| %>
          <li><%= error.capitalize %></li>
        <% end %>
      </ul>
    <% end %>
    <%= button_tag(type: 'submit') do %>
      It's ok!
    <% end %>
  <% end %>
</div>

app/views/users/_edit.html.erb
<% provide(:title, 'Update') %>
<div id="app">
  <div class="user-edit-folder">
    <div class="nav-name-content">
      <h1>Chang your name</h1>
      <%= form_for @user, remote: true do |form| %>
        <%= form.label :name, hidden: :true %>
        <%= form.text_field :name, placeholder: "Your name" %><br>
        <%= form.label :surname, hidden: :true %>
        <%= form.text_field :surname, placeholder: "Your surname" %><br>
        <%= button_tag(type: 'submit', class: "btn btn-sm btn-warning") do %>
          It's ok!
        <% end %>
      <% end %>
    </div>

    <div class="nav-pass-content">
      <h1>Chang your password</h1>
      <%= form_for(@user, url: edit_pass_path, method: :post, remote: true) do |form| %>
        <%= form.label :last_password, hidden: :true %>
        <%= form.password_field :last_password, placeholder: "Last password" %><br>

        <%= form.label :password, hidden: :true %>
        <%= form.password_field :password, placeholder: "New password" %><br>
        <%= form.label :password_confirmation, hidden: :true %>
        <%= form.password_field :password_confirmation, placeholder: "Confirm new password" %><br>
        <%= button_tag(type: 'submit') do %>
          It's ok!
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_friends.html.erb
<% provide(:title, 'Friends') %>
<div id="app">
  <div class="show-all-friends">
    <h1>Friends</h1>
    <hr>
    <% @friends.all.each do |friend| %>
      <div class="one-friend">
        <%= link_to friend, remote: true do %>
          <% if (get_avatar friend).nil? %>
            <figure class="avatar">
              <p><img src="/assets/avatar.jpg"></p>
            </figure>
          <% else %>
            <figure class="avatar">
              <p><img src=<%= "#{get_avatar friend}" %> ></p>
            </figure>
          <% end %>
        <% end %>
        <%= link_to "#{friend.name+' '+friend.surname}", user_path(friend), remote: true %>

        <% unless friend == current_user %>

            <button class="friend-action send-letter" id= <%=friend.id %>>Send message</button>
            <div class="send-message" id=<%="send-message-#{friend.id}" %> >
              <%= form_for(:message, :url => user_messages_path(friend), method: :post, remote: true) do |form| %>
                <%= form.label :text, hidden: :true %>
                <%= form.text_area :text, class: "message-create-body",
                                          placeholder: "Write your message",
                                          autofocus: "true" %> <br>
                <hr class="comment-margin">
                <%= button_tag(type: 'submit') do %>
                  Send
                <% end %>
              <% end %>
              <hr class="comment-margin">
            </div>
          <% if @user == current_user %>
            <%= form_for(:user, url: delete_friend_path, method: :delete, remote: true) do |form| %>
              <%= form.hidden_field 'user_id', :value => friend.id %>
              <%= form.hidden_field 'profile', :value => false %>
              <button class="friend-action" type="submit">Delete friend</button>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <hr>
    <% end %>
  </div>
</div>

app/views/users/_new.html.erb
<% provide(:title, 'Home') %>
<div id="app">
  <div class="root-page">
    <div class="root-content">
    </div>
    <div class="create-user">
      <span class="click-to-create"> New user? </span>
      <%= render '/users/create_form' %>
    </div>
  </div>
</div>

app/views/users/_posts.html.erb
<div class="posts">
  <% @posts.each do |post| %>
    <div class="post" id=<%= "post-#{post.id}" %> >
      <p class="author"><%= link_to @user.name+' '+@user.surname, @user, remote: true %></p>
      <p class="rating">
        <span class="like">
          <%= link_to '+', like_user_post_path(@user, post), method: :post, remote: true %>
          <span class=<%= "plus-#{post.id}" %>><%= like post %></span>
        </span> |
        <span class="dislike">
          <span class=<%= "minus-#{post.id}" %>><%= dislike post %></span>
          <%= link_to '-', dislike_user_post_path(@user, post), method: :post, remote: true %>
        </span>
      </p>
      <p class="date"><%= date_format post.created_at %></p>
      <hr class="line">
      <% unless post.images.empty? %>
      <img src=<%= post.images.last.image.post.url %> class="with" id=<%= @user.id %> >
      <% end %>
      <% unless (get_utube post.text).nil? %>
        <iframe width="420" height="315" frameborder="0" allowfullscreen
                src=<%= get_utube post.text %> ></iframe>
      <% end %>
      <div class="post-content">
        <p class="post-text"><%= post.text %></p>
      </div>
      <% if post_comments(post).all.count == 0 %>
        <p class="to-comment" id=<%= "#{post.id}" %> >Comment</p>
      <% end %>
      <% if current_user == @user %>
        <%= link_to "Delete", user_post_path(@user, post), method: :delete, remote: true, class: "edit-post" %>
        <%#= link_to "Edit", edit_user_post_path(@user, post), remote: true, class: "edit-post" %>
      <% end %>
    </div>

    <div class="comments">
      <% post_comments(post).each do |comment| %>
        <div class="comment" id=<%= "comment-#{comment.id}" %> >
          <p class="author">
            <%= link_to (author comment).name+' '+(author comment).surname, (author comment),
                        remote: true, class: 'author-link' %>
          </p>
          <hr class="line">
          <div class="comment-content">
            <p class="comment-text"><%= comment.text %></p>
          </div>
          <p class="date"><%= date_format comment.created_at %></p>
          <% if current_user == (author comment) %>
            <%= link_to "Delete", user_comment_path(@user, comment),
                        method: :delete, remote: true, class: "edit-comment" %>
          <% end %>
        </div>
        <hr class="comment-margin">
      <% end %>

      <hr class="comment-hr">

      <% unless (post_comments(post).all.count == 0) %>
        <div class=<%= "to-create-comment-#{post.id}" %> >
          <button class="new-comment" id=<%= "#{post.id}" %> >Write your new comment</button>
        </div>
      <% else %>
        <style><%= ".create-comment-#{post.id}" %> {display: none;}</style>
      <% end %>
      <div class=<%= "create-comment-#{post.id}" %> >
        <%= render(partial: '/comments/comment_form', :locals => { :post => post, :comment => @comment}) %>
      </div>
    </div>

  <% end %>
</div>

app/views/users/_show.html.erb
<div id="app">
  <div class="user-show" id=<%= @user.id %>>
    <div class="profile-static">
      <% if (get_avatar @user).nil? %>
        <figure class="default-avatar user-image">
    			<p><img src="/assets/avatar.jpg" class="with" id=<%= @user.id %>></p>
    		</figure>
      <% else %>
        <figure class="avatar">
          <p><img src= <%= "#{get_avatar @user}" %> class="with" id=<%= @user.id %>></p>
        </figure>
      <% end %>

      <% unless current_user == @user %>
        <hr>

        <button class="friend-action send-letter" id= <%=@user.id %>>Send message</button>
        <div class="send-message" id=<%="send-message-#{@user.id}"%> >
          <%= form_for(:message, :url => user_messages_path(@user), method: :post, remote: true) do |form| %>
            <%= form.label :text, hidden: :true %>
            <%= form.text_area :text, class: "message-create-body",
                                      placeholder: "Write your message",
                                      autofocus: "true" %> <br>
            <hr class="comment-margin">
            <%= button_tag(type: 'submit') do %>
              Send
            <% end %>
          <% end %>
          <hr class="comment-margin">
        </div>

        <% if is_friend? @user %>
          <%= form_for(:user, url: delete_friend_path, method: :delete, remote: true) do |form| %>
            <%= form.hidden_field 'user_id', :value => @user.id %>
            <button class="friend-action" type="submit">Delete friend</button>
          <% end %>
        <% else %>
          <%= form_for(:friend_relation, url: add_friend_path, method: :post, remote: true) do |form| %>
            <%= form.hidden_field 'user_id', :value => @user.id %>
            <button class="friend-action" type="submit">Add to friends</button>
          <% end %>
        <% end %>
      <% end %>

      <% unless @friends.all.count == 0 %>
        <hr>

        <div class="friends">
          <p class="friends-h1">Friends <%= link_to "see all", friends_user_path(@user), remote: true %></p>
          <% @friends.all.each do |friend| %>
            <%= link_to friend, remote: true do %>
              <figure class="pfofile-friend">
                <p><img src=<%= "#{ get_ico friend }" %>></p>
                <figcaption><%= friend.name %></figcaption>
              </figure>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="profile-activity">
      <p class="profile-name"><%= @user.name+' '+@user.surname %></p>
      <hr>
      <p class="activity">
        User's activity:
        friends <%= @user.all_friends.count %>;
        posts <%= @user.posts.count %>;
        images <%= @user.images.count %>;
        comments <%= @user.comments.count %>.
      </p>
      <hr>

      <% if current_user == @user %>
        <div class="to-create-post"><button class="new-post">Write your new post</button></div>
        <div class="create-post">
          <%= render(partial: '/posts/post_form', :locals => {:post => @post}) %>
        </div>
        <hr>
      <% end %>

      <%= render(partial: '/users/posts', :locals => {:posts => @posts}) %>

    </div>
  </div>
</div>

app/views/users/create.js.erb
<% if @page == 'profile' %>
  $("<%= escape_javascript(render(partial: 'users/show', :locals => {:post => @post, :posts => @posts, :friends => @friends, :user => @user })) %>")
  .replaceAll("#app");
  $(document).ready(createPostAction);
  $(document).ready(createCommentAction);
  $(document).ready(toCreateCommentAction);
  $(document).ready(addHeightToProfile);
  $(document).ready(showImage);
<% else %>
  $("<%= escape_javascript(render(partial: 'users/new', :locals => {:user => @user })) %>")
  .replaceAll("#app");
  $(document).ready(rootJSAction);
<% end %>

app/views/users/create_friend.js.erb
$("<%= escape_javascript(render(partial: 'users/show', :locals => {:post => @post, :posts => @posts, :friends => @friends, :user => @user })) %>")
.replaceAll("#app");
$(document).ready(createCommentAction);
$(document).ready(toCreateCommentAction);
$(document).ready(addHeightToProfile);
$(document).ready(showImage);

app/views/users/destroy_friend.js.erb
<% unless @profile == 'false' %>
$("<%= escape_javascript(render(partial: 'users/show', :locals => {:post => @post, :posts => @posts, :friends => @friends, :user => @user })) %>")
.replaceAll("#app");
$(document).ready(createCommentAction);
$(document).ready(toCreateCommentAction);
$(document).ready(addHeightToProfile);
$(document).ready(showImage);
<% else %>
$("<%= escape_javascript(render(partial: 'users/friends', :locals => {:friends => @friends, :user => @user })) %>")
.replaceAll("#app");
<% end %>
$(document).ready(sendMessage);

app/views/users/edit_pass.js.erb
$("<%= escape_javascript(render(partial: 'users/show', :locals => {:post => @post, :posts => @posts, :friends => @friends, :user => @user })) %>")
.replaceAll("#app");
$(document).ready(createPostAction);
$(document).ready(createCommentAction);
$(document).ready(toCreateCommentAction);
$(document).ready(addHeightToProfile);
$(document).ready(showImage);

app/views/users/friends.js.erb
$("<%= escape_javascript(render(partial: 'users/friends', :locals => {:friends => @friends, :user => @user })) %>")
.replaceAll("#app");

$(document).ready(toCreateCommentAction);
$(document).ready(sendMessage);

app/views/users/new.html.erb
<%=
  if logged?
    render(partial: 'show', :locals => {:post => @post, :posts => @posts, :friends => @friends, :user => @user })
  else
    render 'new'
  end 
%>

app/views/users/show.js.erb
$("<%= escape_javascript(render(partial: 'users/show', :locals => {:post => @post, :posts => @posts, :friends => @friends, :user => @user })) %>")
.replaceAll("#app");
$(document).ready(createPostAction);
$(document).ready(createCommentAction);
$(document).ready(toCreateCommentAction);
$(document).ready(addHeightToProfile);
$(document).ready(showImage);

app/views/users/update.js.erb
$("<%= escape_javascript(render(partial: 'users/show', :locals => {:post => @post, :posts => @posts, :friends => @friends, :user => @user })) %>")
.replaceAll("#app");
$(document).ready(createPostAction);
$(document).ready(createCommentAction);
$(document).ready(toCreateCommentAction);
$(document).ready(addHeightToProfile);
$(document).ready(showImage);