config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  get    'account_activation',  to: 'users#account_activation'
  get    'password_reset',      to: 'users#password_reset'
  post   'edit_pass',           to: 'users#edit_pass'
  post   'search',              to: 'users#search'
  post   'set',                 to: 'posts#add_next'
  get    'search',              to: 'users#index'
  post   'add_friend',          to: 'users#create_friend'
  delete 'delete_friend',       to: 'users#destroy_friend'
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'
  resources :users do
    resources :posts do
      post "like", on: :member
      post "dislike", on: :member
    end
    resources :images
    resources :comments
    resources :messages
    patch :friends, on: :member
    get :friends, on: :member
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <% if logged? %>
    <%= link_to "Ant-eater", current_user, remote: true, id: "logo-footer" %>
  <% else %>
    <%= link_to "Ant-eater", root_path, method: :get, id: "logo-footer" %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <% if logged? %>
    <%= link_to "Ant-eater", current_user, remote: true, id: "logo" %>
  <% else %>
    <%= link_to "Ant-eater", root_path, method: :get, id: "logo" %>
  <% end %>

  <% if logged? %>
    <%= form_for User.new, :url => search_path, remote: true do |form| %>
      <%= form.label :title, hidden: :true %>
      <%= form.text_field :name, class: "form-control", placeholder: "Search" %>
      <%= button_tag(type: 'submit', hidden: :true) do %>Search!<% end %>
    <% end %>
  <% end %>

  <nav>
    <ul class="header-nav">
      <% if logged? %>
        <li class="dropdown">
          <p>
            <span><%= current_user.surname %></span>
            <img src="/assets/setting.png">
          </p>
          <div class="dropdown-up"></div>
          <ul class="dropdown-menu">
            <%= link_to edit_user_path(current_user), remote: true do %>
              <li>Edit profile</li>
            <% end %>
            <%= link_to logout_path(current_user), method: :delete do %>
              <li>Log out</li>
            <% end %>
          </ul>
        </li>
      <% else %>
        <li class="log-in"><%= link_to "Log in", root_path %></li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/_menu.html.erb
<div class="main-menu">
  <ul>
    <%= link_to current_user, remote: true do %>
      <li>Profile</li>
    <% end %>
    <%= link_to user_messages_path(current_user), remote: true do %>
      <li>Messages</li>
    <% end %>
    <%= link_to user_posts_path(current_user), remote: true do %>
      <li>News</li>
    <% end %>
    <%= link_to friends_user_path(current_user), remote: true do %>
      <li>Friends</li>
    <% end %>
    <%= link_to user_images_path(current_user), remote: true do %>
      <li>Gallery</li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ant-eater</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <div class="main-content">
      <div class="go-up"></div>
      <div class="show-image">
        <%= render '/images/show' %>
      </div>
      <div class="content">
        <div class="menu">
          <% if logged? %>
            <%= render 'layouts/menu' %>
          <% else %>
            <%= render 'sessions/login' %>
          <% end %>
        </div>
        <div class="yield_pages">
          <%= yield %>
        </div>
      </div>
    </div>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>